// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The location and representation of a wallpaper asset.
enum WallpaperSourceKindData: Int {
  case url = 0
  case filePath = 1
  case contentUri = 2
  case bytes = 3
}

/// The display target requested for a wallpaper operation.
enum WallpaperTargetData: Int {
  case home = 0
  case lock = 1
  case both = 2
}

/// The way an image or video should be scaled to fit its target display.
enum WallpaperScaleModeData: Int {
  case centerCrop = 0
  case fitCenter = 1
  case center = 2
  case fill = 3
  case stretch = 4
}

/// The Android application strategy requested by the caller.
enum WallpaperApplyStrategyData: Int {
  case direct = 0
  case systemCropper = 1
  case systemPicker = 2
  case automatic = 3
}

/// The outcome of a complete platform wallpaper operation.
enum OperationStatusData: Int {
  case applied = 0
  case previewOpened = 1
  case awaitingUserConfirmation = 2
  case cancelled = 3
  case failed = 4
  case unsupported = 5
  case foregroundRequired = 6
}

/// The outcome for one wallpaper target within an operation.
enum TargetStatusData: Int {
  case applied = 0
  case failed = 1
  case unsupported = 2
  case notAttempted = 3
}

/// A static, content-provider, or in-memory wallpaper source.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WallpaperSourceData: Hashable {
  var kind: WallpaperSourceKindData? = nil
  var url: String? = nil
  var filePath: String? = nil
  var contentUri: String? = nil
  var bytes: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WallpaperSourceData? {
    let kind: WallpaperSourceKindData? = nilOrValue(pigeonVar_list[0])
    let url: String? = nilOrValue(pigeonVar_list[1])
    let filePath: String? = nilOrValue(pigeonVar_list[2])
    let contentUri: String? = nilOrValue(pigeonVar_list[3])
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])

    return WallpaperSourceData(
      kind: kind,
      url: url,
      filePath: filePath,
      contentUri: contentUri,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      url,
      filePath,
      contentUri,
      bytes,
    ]
  }
  static func == (lhs: WallpaperSourceData, rhs: WallpaperSourceData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Result details for one target display.
///
/// Generated class from Pigeon that represents data sent in messages.
struct TargetResultData: Hashable {
  var status: TargetStatusData? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil
  var errorDetails: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TargetResultData? {
    let status: TargetStatusData? = nilOrValue(pigeonVar_list[0])
    let errorCode: String? = nilOrValue(pigeonVar_list[1])
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])
    let errorDetails: String? = nilOrValue(pigeonVar_list[3])

    return TargetResultData(
      status: status,
      errorCode: errorCode,
      errorMessage: errorMessage,
      errorDetails: errorDetails
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      errorCode,
      errorMessage,
      errorDetails,
    ]
  }
  static func == (lhs: TargetResultData, rhs: TargetResultData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// A truthful, structured result from the host platform.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OperationResultData: Hashable {
  var status: OperationStatusData? = nil
  var requestedTarget: WallpaperTargetData? = nil
  var home: TargetResultData? = nil
  var lock: TargetResultData? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil
  var errorDetails: String? = nil
  var fallbackUsed: Bool? = nil
  var fallbackStrategy: WallpaperApplyStrategyData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OperationResultData? {
    let status: OperationStatusData? = nilOrValue(pigeonVar_list[0])
    let requestedTarget: WallpaperTargetData? = nilOrValue(pigeonVar_list[1])
    let home: TargetResultData? = nilOrValue(pigeonVar_list[2])
    let lock: TargetResultData? = nilOrValue(pigeonVar_list[3])
    let errorCode: String? = nilOrValue(pigeonVar_list[4])
    let errorMessage: String? = nilOrValue(pigeonVar_list[5])
    let errorDetails: String? = nilOrValue(pigeonVar_list[6])
    let fallbackUsed: Bool? = nilOrValue(pigeonVar_list[7])
    let fallbackStrategy: WallpaperApplyStrategyData? = nilOrValue(pigeonVar_list[8])

    return OperationResultData(
      status: status,
      requestedTarget: requestedTarget,
      home: home,
      lock: lock,
      errorCode: errorCode,
      errorMessage: errorMessage,
      errorDetails: errorDetails,
      fallbackUsed: fallbackUsed,
      fallbackStrategy: fallbackStrategy
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      requestedTarget,
      home,
      lock,
      errorCode,
      errorMessage,
      errorDetails,
      fallbackUsed,
      fallbackStrategy,
    ]
  }
  static func == (lhs: OperationResultData, rhs: OperationResultData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Capability snapshot reported by the host platform.
///
/// Generated class from Pigeon that represents data sent in messages.
struct WallpaperCapabilitiesData: Hashable {
  var supportsStaticWallpaper: Bool? = nil
  var supportsLiveWallpaper: Bool? = nil
  var supportsOpenGlLiveWallpaper: Bool? = nil
  var supportsHomeWallpaper: Bool? = nil
  var supportsLockWallpaper: Bool? = nil
  var supportsBothWallpapers: Bool? = nil
  var canSetWallpaper: Bool? = nil
  var hasSystemWallpaperPicker: Bool? = nil
  var requiresForeground: Bool? = nil
  var manufacturer: String? = nil
  var sdkInt: Int64? = nil
  var openGlVersion: String? = nil
  var openGlRenderer: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WallpaperCapabilitiesData? {
    let supportsStaticWallpaper: Bool? = nilOrValue(pigeonVar_list[0])
    let supportsLiveWallpaper: Bool? = nilOrValue(pigeonVar_list[1])
    let supportsOpenGlLiveWallpaper: Bool? = nilOrValue(pigeonVar_list[2])
    let supportsHomeWallpaper: Bool? = nilOrValue(pigeonVar_list[3])
    let supportsLockWallpaper: Bool? = nilOrValue(pigeonVar_list[4])
    let supportsBothWallpapers: Bool? = nilOrValue(pigeonVar_list[5])
    let canSetWallpaper: Bool? = nilOrValue(pigeonVar_list[6])
    let hasSystemWallpaperPicker: Bool? = nilOrValue(pigeonVar_list[7])
    let requiresForeground: Bool? = nilOrValue(pigeonVar_list[8])
    let manufacturer: String? = nilOrValue(pigeonVar_list[9])
    let sdkInt: Int64? = nilOrValue(pigeonVar_list[10])
    let openGlVersion: String? = nilOrValue(pigeonVar_list[11])
    let openGlRenderer: String? = nilOrValue(pigeonVar_list[12])

    return WallpaperCapabilitiesData(
      supportsStaticWallpaper: supportsStaticWallpaper,
      supportsLiveWallpaper: supportsLiveWallpaper,
      supportsOpenGlLiveWallpaper: supportsOpenGlLiveWallpaper,
      supportsHomeWallpaper: supportsHomeWallpaper,
      supportsLockWallpaper: supportsLockWallpaper,
      supportsBothWallpapers: supportsBothWallpapers,
      canSetWallpaper: canSetWallpaper,
      hasSystemWallpaperPicker: hasSystemWallpaperPicker,
      requiresForeground: requiresForeground,
      manufacturer: manufacturer,
      sdkInt: sdkInt,
      openGlVersion: openGlVersion,
      openGlRenderer: openGlRenderer
    )
  }
  func toList() -> [Any?] {
    return [
      supportsStaticWallpaper,
      supportsLiveWallpaper,
      supportsOpenGlLiveWallpaper,
      supportsHomeWallpaper,
      supportsLockWallpaper,
      supportsBothWallpapers,
      canSetWallpaper,
      hasSystemWallpaperPicker,
      requiresForeground,
      manufacturer,
      sdkInt,
      openGlVersion,
      openGlRenderer,
    ]
  }
  static func == (lhs: WallpaperCapabilitiesData, rhs: WallpaperCapabilitiesData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for an image wallpaper operation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct StaticWallpaperRequestData: Hashable {
  var source: WallpaperSourceData? = nil
  var target: WallpaperTargetData? = nil
  var scaleMode: WallpaperScaleModeData? = nil
  var strategy: WallpaperApplyStrategyData? = nil
  var goToHome: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StaticWallpaperRequestData? {
    let source: WallpaperSourceData? = nilOrValue(pigeonVar_list[0])
    let target: WallpaperTargetData? = nilOrValue(pigeonVar_list[1])
    let scaleMode: WallpaperScaleModeData? = nilOrValue(pigeonVar_list[2])
    let strategy: WallpaperApplyStrategyData? = nilOrValue(pigeonVar_list[3])
    let goToHome: Bool? = nilOrValue(pigeonVar_list[4])

    return StaticWallpaperRequestData(
      source: source,
      target: target,
      scaleMode: scaleMode,
      strategy: strategy,
      goToHome: goToHome
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      target,
      scaleMode,
      strategy,
      goToHome,
    ]
  }
  static func == (lhs: StaticWallpaperRequestData, rhs: StaticWallpaperRequestData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for preparing or previewing a video live wallpaper.
///
/// Generated class from Pigeon that represents data sent in messages.
struct VideoWallpaperRequestData: Hashable {
  var source: WallpaperSourceData? = nil
  var target: WallpaperTargetData? = nil
  var scaleMode: WallpaperScaleModeData? = nil
  var goToHome: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoWallpaperRequestData? {
    let source: WallpaperSourceData? = nilOrValue(pigeonVar_list[0])
    let target: WallpaperTargetData? = nilOrValue(pigeonVar_list[1])
    let scaleMode: WallpaperScaleModeData? = nilOrValue(pigeonVar_list[2])
    let goToHome: Bool? = nilOrValue(pigeonVar_list[3])

    return VideoWallpaperRequestData(
      source: source,
      target: target,
      scaleMode: scaleMode,
      goToHome: goToHome
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      target,
      scaleMode,
      goToHome,
    ]
  }
  static func == (lhs: VideoWallpaperRequestData, rhs: VideoWallpaperRequestData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Parameters for applying a shader-based OpenGL live wallpaper.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OpenGlWallpaperRequestData: Hashable {
  var fragmentShader: String? = nil
  var textures: [WallpaperSourceData?]? = nil
  var target: WallpaperTargetData? = nil
  var frameRate: Int64? = nil
  var goToHome: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenGlWallpaperRequestData? {
    let fragmentShader: String? = nilOrValue(pigeonVar_list[0])
    let textures: [WallpaperSourceData?]? = nilOrValue(pigeonVar_list[1])
    let target: WallpaperTargetData? = nilOrValue(pigeonVar_list[2])
    let frameRate: Int64? = nilOrValue(pigeonVar_list[3])
    let goToHome: Bool? = nilOrValue(pigeonVar_list[4])

    return OpenGlWallpaperRequestData(
      fragmentShader: fragmentShader,
      textures: textures,
      target: target,
      frameRate: frameRate,
      goToHome: goToHome
    )
  }
  func toList() -> [Any?] {
    return [
      fragmentShader,
      textures,
      target,
      frameRate,
      goToHome,
    ]
  }
  static func == (lhs: OpenGlWallpaperRequestData, rhs: OpenGlWallpaperRequestData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MaterialYouSupportData: Hashable {
  var isSupported: Bool? = nil
  var androidVersion: String? = nil
  var sdkInt: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MaterialYouSupportData? {
    let isSupported: Bool? = nilOrValue(pigeonVar_list[0])
    let androidVersion: String? = nilOrValue(pigeonVar_list[1])
    let sdkInt: Int64? = nilOrValue(pigeonVar_list[2])

    return MaterialYouSupportData(
      isSupported: isSupported,
      androidVersion: androidVersion,
      sdkInt: sdkInt
    )
  }
  func toList() -> [Any?] {
    return [
      isSupported,
      androidVersion,
      sdkInt,
    ]
  }
  static func == (lhs: MaterialYouSupportData, rhs: MaterialYouSupportData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RotationSourceData: Hashable {
  var source: String? = nil
  var sourceType: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RotationSourceData? {
    let source: String? = nilOrValue(pigeonVar_list[0])
    let sourceType: Int64? = nilOrValue(pigeonVar_list[1])

    return RotationSourceData(
      source: source,
      sourceType: sourceType
    )
  }
  func toList() -> [Any?] {
    return [
      source,
      sourceType,
    ]
  }
  static func == (lhs: RotationSourceData, rhs: RotationSourceData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WallpaperRotationConfigData: Hashable {
  var sources: [RotationSourceData?]? = nil
  var target: Int64? = nil
  var intervalMinutes: Int64? = nil
  var enableIntervalTrigger: Bool? = nil
  var enableChargingTrigger: Bool? = nil
  var enableTimeOfDayTrigger: Bool? = nil
  var activeHoursStart: Int64? = nil
  var activeHoursEnd: Int64? = nil
  var orderType: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WallpaperRotationConfigData? {
    let sources: [RotationSourceData?]? = nilOrValue(pigeonVar_list[0])
    let target: Int64? = nilOrValue(pigeonVar_list[1])
    let intervalMinutes: Int64? = nilOrValue(pigeonVar_list[2])
    let enableIntervalTrigger: Bool? = nilOrValue(pigeonVar_list[3])
    let enableChargingTrigger: Bool? = nilOrValue(pigeonVar_list[4])
    let enableTimeOfDayTrigger: Bool? = nilOrValue(pigeonVar_list[5])
    let activeHoursStart: Int64? = nilOrValue(pigeonVar_list[6])
    let activeHoursEnd: Int64? = nilOrValue(pigeonVar_list[7])
    let orderType: Int64? = nilOrValue(pigeonVar_list[8])

    return WallpaperRotationConfigData(
      sources: sources,
      target: target,
      intervalMinutes: intervalMinutes,
      enableIntervalTrigger: enableIntervalTrigger,
      enableChargingTrigger: enableChargingTrigger,
      enableTimeOfDayTrigger: enableTimeOfDayTrigger,
      activeHoursStart: activeHoursStart,
      activeHoursEnd: activeHoursEnd,
      orderType: orderType
    )
  }
  func toList() -> [Any?] {
    return [
      sources,
      target,
      intervalMinutes,
      enableIntervalTrigger,
      enableChargingTrigger,
      enableTimeOfDayTrigger,
      activeHoursStart,
      activeHoursEnd,
      orderType,
    ]
  }
  static func == (lhs: WallpaperRotationConfigData, rhs: WallpaperRotationConfigData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WallpaperRotationStatusData: Hashable {
  var isRunning: Bool? = nil
  var nextRunEpochMs: Int64? = nil
  var currentIndex: Int64? = nil
  var cachedCount: Int64? = nil
  var totalCount: Int64? = nil
  var lastError: String? = nil
  var effectiveIntervalMinutes: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WallpaperRotationStatusData? {
    let isRunning: Bool? = nilOrValue(pigeonVar_list[0])
    let nextRunEpochMs: Int64? = nilOrValue(pigeonVar_list[1])
    let currentIndex: Int64? = nilOrValue(pigeonVar_list[2])
    let cachedCount: Int64? = nilOrValue(pigeonVar_list[3])
    let totalCount: Int64? = nilOrValue(pigeonVar_list[4])
    let lastError: String? = nilOrValue(pigeonVar_list[5])
    let effectiveIntervalMinutes: Int64? = nilOrValue(pigeonVar_list[6])

    return WallpaperRotationStatusData(
      isRunning: isRunning,
      nextRunEpochMs: nextRunEpochMs,
      currentIndex: currentIndex,
      cachedCount: cachedCount,
      totalCount: totalCount,
      lastError: lastError,
      effectiveIntervalMinutes: effectiveIntervalMinutes
    )
  }
  func toList() -> [Any?] {
    return [
      isRunning,
      nextRunEpochMs,
      currentIndex,
      cachedCount,
      totalCount,
      lastError,
      effectiveIntervalMinutes,
    ]
  }
  static func == (lhs: WallpaperRotationStatusData, rhs: WallpaperRotationStatusData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

private class PigeonApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WallpaperSourceKindData(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WallpaperTargetData(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WallpaperScaleModeData(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return WallpaperApplyStrategyData(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OperationStatusData(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TargetStatusData(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return WallpaperSourceData.fromList(self.readValue() as! [Any?])
    case 136:
      return TargetResultData.fromList(self.readValue() as! [Any?])
    case 137:
      return OperationResultData.fromList(self.readValue() as! [Any?])
    case 138:
      return WallpaperCapabilitiesData.fromList(self.readValue() as! [Any?])
    case 139:
      return StaticWallpaperRequestData.fromList(self.readValue() as! [Any?])
    case 140:
      return VideoWallpaperRequestData.fromList(self.readValue() as! [Any?])
    case 141:
      return OpenGlWallpaperRequestData.fromList(self.readValue() as! [Any?])
    case 142:
      return MaterialYouSupportData.fromList(self.readValue() as! [Any?])
    case 143:
      return RotationSourceData.fromList(self.readValue() as! [Any?])
    case 144:
      return WallpaperRotationConfigData.fromList(self.readValue() as! [Any?])
    case 145:
      return WallpaperRotationStatusData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? WallpaperSourceKindData {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? WallpaperTargetData {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? WallpaperScaleModeData {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? WallpaperApplyStrategyData {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? OperationStatusData {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? TargetStatusData {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? WallpaperSourceData {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? TargetResultData {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? OperationResultData {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? WallpaperCapabilitiesData {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? StaticWallpaperRequestData {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? VideoWallpaperRequestData {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? OpenGlWallpaperRequestData {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? MaterialYouSupportData {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? RotationSourceData {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? WallpaperRotationConfigData {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? WallpaperRotationStatusData {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonApiPigeonCodecWriter(data: data)
  }
}

class PigeonApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonApiPigeonCodec(readerWriter: PigeonApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WallpaperApi {
  func getPlatformVersion(completion: @escaping (Result<String, Error>) -> Void)
  func checkMaterialYouSupport(completion: @escaping (Result<MaterialYouSupportData, Error>) -> Void)
  /// Returns the platform's structured wallpaper capabilities.
  func getCapabilities(completion: @escaping (Result<WallpaperCapabilitiesData, Error>) -> Void)
  /// Applies a static wallpaper using the structured 3.2 transport contract.
  func applyWallpaper(request: StaticWallpaperRequestData, completion: @escaping (Result<OperationResultData, Error>) -> Void)
  /// Prepares a video live wallpaper without claiming that it was applied.
  func prepareVideoWallpaper(request: VideoWallpaperRequestData, completion: @escaping (Result<OperationResultData, Error>) -> Void)
  /// Opens the live-wallpaper UI and reports that distinct outcome.
  func openLiveWallpaperPreview(request: VideoWallpaperRequestData, completion: @escaping (Result<OperationResultData, Error>) -> Void)
  /// Applies a shader-based OpenGL live wallpaper.
  func applyOpenGlWallpaper(request: OpenGlWallpaperRequestData, completion: @escaping (Result<OperationResultData, Error>) -> Void)
  /// Legacy 3.1 endpoints remain until their facade adapters migrate in Task 5.
  func setHomeWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLockWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setBothWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setWallpaper(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setHomeWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLockWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setBothWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setMaterialYouWallpaper(url: String, goToHome: Bool, enableEffects: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLiveWallpaper(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func openWallpaperChooser(completion: @escaping (Result<Bool, Error>) -> Void)
  func downloadWallpaper(url: String, completion: @escaping (Result<Bool, Error>) -> Void)
  func startWallpaperRotation(config: WallpaperRotationConfigData, completion: @escaping (Result<Bool, Error>) -> Void)
  func stopWallpaperRotation(completion: @escaping (Result<Bool, Error>) -> Void)
  func getWallpaperRotationStatus(completion: @escaping (Result<WallpaperRotationStatusData, Error>) -> Void)
  func rotateWallpaperNow(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WallpaperApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `WallpaperApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WallpaperApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        api.getPlatformVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
    let checkMaterialYouSupportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.checkMaterialYouSupport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkMaterialYouSupportChannel.setMessageHandler { _, reply in
        api.checkMaterialYouSupport { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkMaterialYouSupportChannel.setMessageHandler(nil)
    }
    /// Returns the platform's structured wallpaper capabilities.
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        api.getCapabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    /// Applies a static wallpaper using the structured 3.2 transport contract.
    let applyWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.applyWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! StaticWallpaperRequestData
        api.applyWallpaper(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      applyWallpaperChannel.setMessageHandler(nil)
    }
    /// Prepares a video live wallpaper without claiming that it was applied.
    let prepareVideoWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.prepareVideoWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareVideoWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoWallpaperRequestData
        api.prepareVideoWallpaper(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      prepareVideoWallpaperChannel.setMessageHandler(nil)
    }
    /// Opens the live-wallpaper UI and reports that distinct outcome.
    let openLiveWallpaperPreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openLiveWallpaperPreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openLiveWallpaperPreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoWallpaperRequestData
        api.openLiveWallpaperPreview(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openLiveWallpaperPreviewChannel.setMessageHandler(nil)
    }
    /// Applies a shader-based OpenGL live wallpaper.
    let applyOpenGlWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.applyOpenGlWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyOpenGlWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OpenGlWallpaperRequestData
        api.applyOpenGlWallpaper(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      applyOpenGlWallpaperChannel.setMessageHandler(nil)
    }
    /// Legacy 3.1 endpoints remain until their facade adapters migrate in Task 5.
    let setHomeWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHomeWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setHomeWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setHomeWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setLockWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLockWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLockWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLockWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setBothWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBothWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setBothWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBothWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setWallpaper(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWallpaperChannel.setMessageHandler(nil)
    }
    let setHomeWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHomeWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setHomeWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setHomeWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setLockWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLockWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLockWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLockWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setBothWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBothWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setBothWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBothWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setMaterialYouWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setMaterialYouWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaterialYouWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        let enableEffectsArg = args[2] as! Bool
        api.setMaterialYouWallpaper(url: urlArg, goToHome: goToHomeArg, enableEffects: enableEffectsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMaterialYouWallpaperChannel.setMessageHandler(nil)
    }
    let setLiveWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLiveWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLiveWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLiveWallpaper(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLiveWallpaperChannel.setMessageHandler(nil)
    }
    let openWallpaperChooserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openWallpaperChooser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openWallpaperChooserChannel.setMessageHandler { _, reply in
        api.openWallpaperChooser { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openWallpaperChooserChannel.setMessageHandler(nil)
    }
    let downloadWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.downloadWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.downloadWallpaper(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadWallpaperChannel.setMessageHandler(nil)
    }
    let startWallpaperRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.startWallpaperRotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startWallpaperRotationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! WallpaperRotationConfigData
        api.startWallpaperRotation(config: configArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startWallpaperRotationChannel.setMessageHandler(nil)
    }
    let stopWallpaperRotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.stopWallpaperRotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopWallpaperRotationChannel.setMessageHandler { _, reply in
        api.stopWallpaperRotation { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopWallpaperRotationChannel.setMessageHandler(nil)
    }
    let getWallpaperRotationStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getWallpaperRotationStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getWallpaperRotationStatusChannel.setMessageHandler { _, reply in
        api.getWallpaperRotationStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getWallpaperRotationStatusChannel.setMessageHandler(nil)
    }
    let rotateWallpaperNowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.rotateWallpaperNow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rotateWallpaperNowChannel.setMessageHandler { _, reply in
        api.rotateWallpaperNow { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      rotateWallpaperNowChannel.setMessageHandler(nil)
    }
  }
}
