// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct MaterialYouSupportData: Hashable {
  var isSupported: Bool? = nil
  var androidVersion: String? = nil
  var sdkInt: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MaterialYouSupportData? {
    let isSupported: Bool? = nilOrValue(pigeonVar_list[0])
    let androidVersion: String? = nilOrValue(pigeonVar_list[1])
    let sdkInt: Int64? = nilOrValue(pigeonVar_list[2])

    return MaterialYouSupportData(
      isSupported: isSupported,
      androidVersion: androidVersion,
      sdkInt: sdkInt
    )
  }
  func toList() -> [Any?] {
    return [
      isSupported,
      androidVersion,
      sdkInt,
    ]
  }
  static func == (lhs: MaterialYouSupportData, rhs: MaterialYouSupportData) -> Bool {
    return deepEqualsPigeonApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonApi(value: toList(), hasher: &hasher)
  }
}

private class PigeonApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MaterialYouSupportData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MaterialYouSupportData {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonApiPigeonCodecWriter(data: data)
  }
}

class PigeonApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonApiPigeonCodec(readerWriter: PigeonApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WallpaperApi {
  func getPlatformVersion(completion: @escaping (Result<String, Error>) -> Void)
  func checkMaterialYouSupport(completion: @escaping (Result<MaterialYouSupportData, Error>) -> Void)
  func setHomeWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLockWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setBothWallpaperFromUrl(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setWallpaper(url: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setHomeWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLockWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setBothWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setWallpaperFromFile(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setMaterialYouWallpaper(url: String, goToHome: Bool, enableEffects: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func setLiveWallpaper(filePath: String, goToHome: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
  func openWallpaperChooser(completion: @escaping (Result<Bool, Error>) -> Void)
  func downloadWallpaper(url: String, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WallpaperApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonApiPigeonCodec.shared }
  /// Sets up an instance of `WallpaperApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WallpaperApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPlatformVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getPlatformVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPlatformVersionChannel.setMessageHandler { _, reply in
        api.getPlatformVersion { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPlatformVersionChannel.setMessageHandler(nil)
    }
    let checkMaterialYouSupportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.checkMaterialYouSupport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkMaterialYouSupportChannel.setMessageHandler { _, reply in
        api.checkMaterialYouSupport { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkMaterialYouSupportChannel.setMessageHandler(nil)
    }
    let setHomeWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHomeWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setHomeWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setHomeWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setLockWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLockWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLockWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLockWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setBothWallpaperFromUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBothWallpaperFromUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setBothWallpaperFromUrl(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBothWallpaperFromUrlChannel.setMessageHandler(nil)
    }
    let setWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setWallpaper(url: urlArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWallpaperChannel.setMessageHandler(nil)
    }
    let setHomeWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHomeWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setHomeWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setHomeWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setLockWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLockWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLockWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLockWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setBothWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setBothWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setBothWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setBothWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setWallpaperFromFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaperFromFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setWallpaperFromFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setWallpaperFromFile(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setWallpaperFromFileChannel.setMessageHandler(nil)
    }
    let setMaterialYouWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setMaterialYouWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMaterialYouWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        let enableEffectsArg = args[2] as! Bool
        api.setMaterialYouWallpaper(url: urlArg, goToHome: goToHomeArg, enableEffects: enableEffectsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setMaterialYouWallpaperChannel.setMessageHandler(nil)
    }
    let setLiveWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLiveWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLiveWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let goToHomeArg = args[1] as! Bool
        api.setLiveWallpaper(filePath: filePathArg, goToHome: goToHomeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLiveWallpaperChannel.setMessageHandler(nil)
    }
    let openWallpaperChooserChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openWallpaperChooser\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openWallpaperChooserChannel.setMessageHandler { _, reply in
        api.openWallpaperChooser { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openWallpaperChooserChannel.setMessageHandler(nil)
    }
    let downloadWallpaperChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.async_wallpaper.WallpaperApi.downloadWallpaper\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      downloadWallpaperChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        api.downloadWallpaper(url: urlArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      downloadWallpaperChannel.setMessageHandler(nil)
    }
  }
}
