// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.codenameakshay.async_wallpaper

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private fun deepEqualsPigeonApi(a: Any?, b: Any?): Boolean {
  if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
  }
  if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
  }
  if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
  }
  if (a is DoubleArray && b is DoubleArray) {
      return a.contentEquals(b)
  }
  if (a is Array<*> && b is Array<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsPigeonApi(a[it], b[it]) }
  }
  if (a is List<*> && b is List<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsPigeonApi(a[it], b[it]) }
  }
  if (a is Map<*, *> && b is Map<*, *>) {
    return a.size == b.size && a.all {
        (b as Map<Any?, Any?>).containsKey(it.key) &&
        deepEqualsPigeonApi(it.value, b[it.key])
    }
  }
  return a == b
}
    

/** Generated class from Pigeon that represents data sent in messages. */
data class MaterialYouSupportData (
  val isSupported: Boolean? = null,
  val androidVersion: String? = null,
  val sdkInt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MaterialYouSupportData {
      val isSupported = pigeonVar_list[0] as Boolean?
      val androidVersion = pigeonVar_list[1] as String?
      val sdkInt = pigeonVar_list[2] as Long?
      return MaterialYouSupportData(isSupported, androidVersion, sdkInt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isSupported,
      androidVersion,
      sdkInt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MaterialYouSupportData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RotationSourceData (
  val source: String? = null,
  val sourceType: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RotationSourceData {
      val source = pigeonVar_list[0] as String?
      val sourceType = pigeonVar_list[1] as Long?
      return RotationSourceData(source, sourceType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      sourceType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RotationSourceData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallpaperRotationConfigData (
  val sources: List<RotationSourceData?>? = null,
  val target: Long? = null,
  val intervalMinutes: Long? = null,
  val enableIntervalTrigger: Boolean? = null,
  val enableChargingTrigger: Boolean? = null,
  val enableTimeOfDayTrigger: Boolean? = null,
  val activeHoursStart: Long? = null,
  val activeHoursEnd: Long? = null,
  val orderType: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperRotationConfigData {
      val sources = pigeonVar_list[0] as List<RotationSourceData?>?
      val target = pigeonVar_list[1] as Long?
      val intervalMinutes = pigeonVar_list[2] as Long?
      val enableIntervalTrigger = pigeonVar_list[3] as Boolean?
      val enableChargingTrigger = pigeonVar_list[4] as Boolean?
      val enableTimeOfDayTrigger = pigeonVar_list[5] as Boolean?
      val activeHoursStart = pigeonVar_list[6] as Long?
      val activeHoursEnd = pigeonVar_list[7] as Long?
      val orderType = pigeonVar_list[8] as Long?
      return WallpaperRotationConfigData(sources, target, intervalMinutes, enableIntervalTrigger, enableChargingTrigger, enableTimeOfDayTrigger, activeHoursStart, activeHoursEnd, orderType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sources,
      target,
      intervalMinutes,
      enableIntervalTrigger,
      enableChargingTrigger,
      enableTimeOfDayTrigger,
      activeHoursStart,
      activeHoursEnd,
      orderType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperRotationConfigData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallpaperRotationStatusData (
  val isRunning: Boolean? = null,
  val nextRunEpochMs: Long? = null,
  val currentIndex: Long? = null,
  val cachedCount: Long? = null,
  val totalCount: Long? = null,
  val lastError: String? = null,
  val effectiveIntervalMinutes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperRotationStatusData {
      val isRunning = pigeonVar_list[0] as Boolean?
      val nextRunEpochMs = pigeonVar_list[1] as Long?
      val currentIndex = pigeonVar_list[2] as Long?
      val cachedCount = pigeonVar_list[3] as Long?
      val totalCount = pigeonVar_list[4] as Long?
      val lastError = pigeonVar_list[5] as String?
      val effectiveIntervalMinutes = pigeonVar_list[6] as Long?
      return WallpaperRotationStatusData(isRunning, nextRunEpochMs, currentIndex, cachedCount, totalCount, lastError, effectiveIntervalMinutes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      nextRunEpochMs,
      currentIndex,
      cachedCount,
      totalCount,
      lastError,
      effectiveIntervalMinutes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperRotationStatusData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MaterialYouSupportData.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RotationSourceData.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperRotationConfigData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperRotationStatusData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MaterialYouSupportData -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RotationSourceData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WallpaperRotationConfigData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is WallpaperRotationStatusData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WallpaperApi {
  fun getPlatformVersion(callback: (Result<String>) -> Unit)
  fun checkMaterialYouSupport(callback: (Result<MaterialYouSupportData>) -> Unit)
  fun setHomeWallpaperFromUrl(url: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setLockWallpaperFromUrl(url: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setBothWallpaperFromUrl(url: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setWallpaper(url: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setHomeWallpaperFromFile(filePath: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setLockWallpaperFromFile(filePath: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setBothWallpaperFromFile(filePath: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setWallpaperFromFile(filePath: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setMaterialYouWallpaper(url: String, goToHome: Boolean, enableEffects: Boolean, callback: (Result<Boolean>) -> Unit)
  fun setLiveWallpaper(filePath: String, goToHome: Boolean, callback: (Result<Boolean>) -> Unit)
  fun openWallpaperChooser(callback: (Result<Boolean>) -> Unit)
  fun startWallpaperRotation(config: WallpaperRotationConfigData, callback: (Result<Boolean>) -> Unit)
  fun stopWallpaperRotation(callback: (Result<Boolean>) -> Unit)
  fun getWallpaperRotationStatus(callback: (Result<WallpaperRotationStatusData>) -> Unit)
  fun rotateWallpaperNow(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by WallpaperApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `WallpaperApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WallpaperApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformVersion{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.checkMaterialYouSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkMaterialYouSupport{ result: Result<MaterialYouSupportData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setHomeWallpaperFromUrl(urlArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setLockWallpaperFromUrl(urlArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setBothWallpaperFromUrl(urlArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setWallpaper(urlArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setHomeWallpaperFromFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setHomeWallpaperFromFile(filePathArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLockWallpaperFromFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setLockWallpaperFromFile(filePathArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setBothWallpaperFromFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setBothWallpaperFromFile(filePathArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setWallpaperFromFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setWallpaperFromFile(filePathArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setMaterialYouWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            val enableEffectsArg = args[2] as Boolean
            api.setMaterialYouWallpaper(urlArg, goToHomeArg, enableEffectsArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setLiveWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val goToHomeArg = args[1] as Boolean
            api.setLiveWallpaper(filePathArg, goToHomeArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openWallpaperChooser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openWallpaperChooser{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.startWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as WallpaperRotationConfigData
            api.startWallpaperRotation(configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.stopWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopWallpaperRotation{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getWallpaperRotationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getWallpaperRotationStatus{ result: Result<WallpaperRotationStatusData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.rotateWallpaperNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.rotateWallpaperNow{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
