// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.codenameakshay.async_wallpaper

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private fun deepEqualsPigeonApi(a: Any?, b: Any?): Boolean {
  if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
  }
  if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
  }
  if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
  }
  if (a is DoubleArray && b is DoubleArray) {
      return a.contentEquals(b)
  }
  if (a is Array<*> && b is Array<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsPigeonApi(a[it], b[it]) }
  }
  if (a is List<*> && b is List<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsPigeonApi(a[it], b[it]) }
  }
  if (a is Map<*, *> && b is Map<*, *>) {
    return a.size == b.size && a.all {
        (b as Map<Any?, Any?>).containsKey(it.key) &&
        deepEqualsPigeonApi(it.value, b[it.key])
    }
  }
  return a == b
}
    

/** The location and representation of a wallpaper asset. */
enum class WallpaperSourceKindData(val raw: Int) {
  URL(0),
  FILE_PATH(1),
  CONTENT_URI(2),
  BYTES(3);

  companion object {
    fun ofRaw(raw: Int): WallpaperSourceKindData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The display target requested for a wallpaper operation. */
enum class WallpaperTargetData(val raw: Int) {
  HOME(0),
  LOCK(1),
  BOTH(2);

  companion object {
    fun ofRaw(raw: Int): WallpaperTargetData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The way an image or video should be scaled to fit its target display. */
enum class WallpaperScaleModeData(val raw: Int) {
  CENTER_CROP(0),
  FIT_CENTER(1),
  CENTER(2),
  FILL(3),
  STRETCH(4);

  companion object {
    fun ofRaw(raw: Int): WallpaperScaleModeData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The Android application strategy requested by the caller. */
enum class WallpaperApplyStrategyData(val raw: Int) {
  DIRECT(0),
  SYSTEM_CROPPER(1),
  SYSTEM_PICKER(2),
  AUTOMATIC(3);

  companion object {
    fun ofRaw(raw: Int): WallpaperApplyStrategyData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The outcome of a complete platform wallpaper operation. */
enum class OperationStatusData(val raw: Int) {
  APPLIED(0),
  PREVIEW_OPENED(1),
  AWAITING_USER_CONFIRMATION(2),
  CANCELLED(3),
  FAILED(4),
  UNSUPPORTED(5),
  FOREGROUND_REQUIRED(6);

  companion object {
    fun ofRaw(raw: Int): OperationStatusData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The outcome for one wallpaper target within an operation. */
enum class TargetStatusData(val raw: Int) {
  APPLIED(0),
  FAILED(1),
  UNSUPPORTED(2),
  NOT_ATTEMPTED(3);

  companion object {
    fun ofRaw(raw: Int): TargetStatusData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The location and representation of a rotation playlist entry. */
enum class RotationSourceTypeData(val raw: Int) {
  URL(0),
  FILE(1);

  companion object {
    fun ofRaw(raw: Int): RotationSourceTypeData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** The order in which rotation playlist entries are applied. */
enum class RotationOrderData(val raw: Int) {
  SEQUENTIAL(0),
  SHUFFLE(1);

  companion object {
    fun ofRaw(raw: Int): RotationOrderData? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A static, content-provider, or in-memory wallpaper source.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WallpaperSourceData (
  val kind: WallpaperSourceKindData? = null,
  val url: String? = null,
  val filePath: String? = null,
  val contentUri: String? = null,
  val bytes: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperSourceData {
      val kind = pigeonVar_list[0] as WallpaperSourceKindData?
      val url = pigeonVar_list[1] as String?
      val filePath = pigeonVar_list[2] as String?
      val contentUri = pigeonVar_list[3] as String?
      val bytes = pigeonVar_list[4] as ByteArray?
      return WallpaperSourceData(kind, url, filePath, contentUri, bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      url,
      filePath,
      contentUri,
      bytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperSourceData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Result details for one target display.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TargetResultData (
  val status: TargetStatusData? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null,
  val errorDetails: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TargetResultData {
      val status = pigeonVar_list[0] as TargetStatusData?
      val errorCode = pigeonVar_list[1] as String?
      val errorMessage = pigeonVar_list[2] as String?
      val errorDetails = pigeonVar_list[3] as String?
      return TargetResultData(status, errorCode, errorMessage, errorDetails)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      errorCode,
      errorMessage,
      errorDetails,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TargetResultData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Structured result, including per-target outcomes, reported by the host platform.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OperationResultData (
  val status: OperationStatusData? = null,
  val requestedTarget: WallpaperTargetData? = null,
  val home: TargetResultData? = null,
  val lock: TargetResultData? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null,
  val errorDetails: String? = null,
  val fallbackUsed: Boolean? = null,
  val fallbackStrategy: WallpaperApplyStrategyData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OperationResultData {
      val status = pigeonVar_list[0] as OperationStatusData?
      val requestedTarget = pigeonVar_list[1] as WallpaperTargetData?
      val home = pigeonVar_list[2] as TargetResultData?
      val lock = pigeonVar_list[3] as TargetResultData?
      val errorCode = pigeonVar_list[4] as String?
      val errorMessage = pigeonVar_list[5] as String?
      val errorDetails = pigeonVar_list[6] as String?
      val fallbackUsed = pigeonVar_list[7] as Boolean?
      val fallbackStrategy = pigeonVar_list[8] as WallpaperApplyStrategyData?
      return OperationResultData(status, requestedTarget, home, lock, errorCode, errorMessage, errorDetails, fallbackUsed, fallbackStrategy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      requestedTarget,
      home,
      lock,
      errorCode,
      errorMessage,
      errorDetails,
      fallbackUsed,
      fallbackStrategy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OperationResultData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Capability snapshot reported by the host platform.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WallpaperCapabilitiesData (
  val supportsStaticWallpaper: Boolean? = null,
  val supportsLiveWallpaper: Boolean? = null,
  val supportsOpenGlLiveWallpaper: Boolean? = null,
  val supportsHomeWallpaper: Boolean? = null,
  val supportsLockWallpaper: Boolean? = null,
  val supportsBothWallpapers: Boolean? = null,
  val canSetWallpaper: Boolean? = null,
  val hasSystemWallpaperPicker: Boolean? = null,
  val requiresForeground: Boolean? = null,
  val manufacturer: String? = null,
  val sdkInt: Long? = null,
  val openGlVersion: String? = null,
  val openGlRenderer: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperCapabilitiesData {
      val supportsStaticWallpaper = pigeonVar_list[0] as Boolean?
      val supportsLiveWallpaper = pigeonVar_list[1] as Boolean?
      val supportsOpenGlLiveWallpaper = pigeonVar_list[2] as Boolean?
      val supportsHomeWallpaper = pigeonVar_list[3] as Boolean?
      val supportsLockWallpaper = pigeonVar_list[4] as Boolean?
      val supportsBothWallpapers = pigeonVar_list[5] as Boolean?
      val canSetWallpaper = pigeonVar_list[6] as Boolean?
      val hasSystemWallpaperPicker = pigeonVar_list[7] as Boolean?
      val requiresForeground = pigeonVar_list[8] as Boolean?
      val manufacturer = pigeonVar_list[9] as String?
      val sdkInt = pigeonVar_list[10] as Long?
      val openGlVersion = pigeonVar_list[11] as String?
      val openGlRenderer = pigeonVar_list[12] as String?
      return WallpaperCapabilitiesData(supportsStaticWallpaper, supportsLiveWallpaper, supportsOpenGlLiveWallpaper, supportsHomeWallpaper, supportsLockWallpaper, supportsBothWallpapers, canSetWallpaper, hasSystemWallpaperPicker, requiresForeground, manufacturer, sdkInt, openGlVersion, openGlRenderer)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      supportsStaticWallpaper,
      supportsLiveWallpaper,
      supportsOpenGlLiveWallpaper,
      supportsHomeWallpaper,
      supportsLockWallpaper,
      supportsBothWallpapers,
      canSetWallpaper,
      hasSystemWallpaperPicker,
      requiresForeground,
      manufacturer,
      sdkInt,
      openGlVersion,
      openGlRenderer,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperCapabilitiesData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Parameters for an image wallpaper operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StaticWallpaperRequestData (
  val source: WallpaperSourceData? = null,
  val target: WallpaperTargetData? = null,
  val scaleMode: WallpaperScaleModeData? = null,
  val strategy: WallpaperApplyStrategyData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StaticWallpaperRequestData {
      val source = pigeonVar_list[0] as WallpaperSourceData?
      val target = pigeonVar_list[1] as WallpaperTargetData?
      val scaleMode = pigeonVar_list[2] as WallpaperScaleModeData?
      val strategy = pigeonVar_list[3] as WallpaperApplyStrategyData?
      return StaticWallpaperRequestData(source, target, scaleMode, strategy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      target,
      scaleMode,
      strategy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StaticWallpaperRequestData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Parameters for preparing or previewing a video live wallpaper.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VideoWallpaperRequestData (
  val source: WallpaperSourceData? = null,
  val target: WallpaperTargetData? = null,
  val scaleMode: WallpaperScaleModeData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoWallpaperRequestData {
      val source = pigeonVar_list[0] as WallpaperSourceData?
      val target = pigeonVar_list[1] as WallpaperTargetData?
      val scaleMode = pigeonVar_list[2] as WallpaperScaleModeData?
      return VideoWallpaperRequestData(source, target, scaleMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      target,
      scaleMode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is VideoWallpaperRequestData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Parameters for applying a shader-based OpenGL live wallpaper.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OpenGlWallpaperRequestData (
  val fragmentShader: String? = null,
  val textures: List<WallpaperSourceData?>? = null,
  val target: WallpaperTargetData? = null,
  val frameRate: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenGlWallpaperRequestData {
      val fragmentShader = pigeonVar_list[0] as String?
      val textures = pigeonVar_list[1] as List<WallpaperSourceData?>?
      val target = pigeonVar_list[2] as WallpaperTargetData?
      val frameRate = pigeonVar_list[3] as Long?
      return OpenGlWallpaperRequestData(fragmentShader, textures, target, frameRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fragmentShader,
      textures,
      target,
      frameRate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is OpenGlWallpaperRequestData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MaterialYouSupportData (
  val isSupported: Boolean? = null,
  val androidVersion: String? = null,
  val sdkInt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MaterialYouSupportData {
      val isSupported = pigeonVar_list[0] as Boolean?
      val androidVersion = pigeonVar_list[1] as String?
      val sdkInt = pigeonVar_list[2] as Long?
      return MaterialYouSupportData(isSupported, androidVersion, sdkInt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isSupported,
      androidVersion,
      sdkInt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MaterialYouSupportData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RotationSourceData (
  val source: String? = null,
  val sourceType: RotationSourceTypeData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RotationSourceData {
      val source = pigeonVar_list[0] as String?
      val sourceType = pigeonVar_list[1] as RotationSourceTypeData?
      return RotationSourceData(source, sourceType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      sourceType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RotationSourceData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallpaperRotationConfigData (
  val sources: List<RotationSourceData?>? = null,
  val target: WallpaperTargetData? = null,
  val intervalMinutes: Long? = null,
  val enableIntervalTrigger: Boolean? = null,
  val enableChargingTrigger: Boolean? = null,
  val enableTimeOfDayTrigger: Boolean? = null,
  val activeHoursStart: Long? = null,
  val activeHoursEnd: Long? = null,
  val orderType: RotationOrderData? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperRotationConfigData {
      val sources = pigeonVar_list[0] as List<RotationSourceData?>?
      val target = pigeonVar_list[1] as WallpaperTargetData?
      val intervalMinutes = pigeonVar_list[2] as Long?
      val enableIntervalTrigger = pigeonVar_list[3] as Boolean?
      val enableChargingTrigger = pigeonVar_list[4] as Boolean?
      val enableTimeOfDayTrigger = pigeonVar_list[5] as Boolean?
      val activeHoursStart = pigeonVar_list[6] as Long?
      val activeHoursEnd = pigeonVar_list[7] as Long?
      val orderType = pigeonVar_list[8] as RotationOrderData?
      return WallpaperRotationConfigData(sources, target, intervalMinutes, enableIntervalTrigger, enableChargingTrigger, enableTimeOfDayTrigger, activeHoursStart, activeHoursEnd, orderType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sources,
      target,
      intervalMinutes,
      enableIntervalTrigger,
      enableChargingTrigger,
      enableTimeOfDayTrigger,
      activeHoursStart,
      activeHoursEnd,
      orderType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperRotationConfigData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WallpaperRotationStatusData (
  val isRunning: Boolean? = null,
  val nextRunEpochMs: Long? = null,
  val currentIndex: Long? = null,
  val cachedCount: Long? = null,
  val totalCount: Long? = null,
  val lastError: String? = null,
  val effectiveIntervalMinutes: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WallpaperRotationStatusData {
      val isRunning = pigeonVar_list[0] as Boolean?
      val nextRunEpochMs = pigeonVar_list[1] as Long?
      val currentIndex = pigeonVar_list[2] as Long?
      val cachedCount = pigeonVar_list[3] as Long?
      val totalCount = pigeonVar_list[4] as Long?
      val lastError = pigeonVar_list[5] as String?
      val effectiveIntervalMinutes = pigeonVar_list[6] as Long?
      return WallpaperRotationStatusData(isRunning, nextRunEpochMs, currentIndex, cachedCount, totalCount, lastError, effectiveIntervalMinutes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isRunning,
      nextRunEpochMs,
      currentIndex,
      cachedCount,
      totalCount,
      lastError,
      effectiveIntervalMinutes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WallpaperRotationStatusData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsPigeonApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WallpaperSourceKindData.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WallpaperTargetData.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WallpaperScaleModeData.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          WallpaperApplyStrategyData.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          OperationStatusData.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          TargetStatusData.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RotationSourceTypeData.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RotationOrderData.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperSourceData.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TargetResultData.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OperationResultData.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperCapabilitiesData.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StaticWallpaperRequestData.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoWallpaperRequestData.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenGlWallpaperRequestData.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MaterialYouSupportData.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RotationSourceData.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperRotationConfigData.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WallpaperRotationStatusData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is WallpaperSourceKindData -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is WallpaperTargetData -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is WallpaperScaleModeData -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is WallpaperApplyStrategyData -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is OperationStatusData -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is TargetStatusData -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is RotationSourceTypeData -> {
        stream.write(135)
        writeValue(stream, value.raw)
      }
      is RotationOrderData -> {
        stream.write(136)
        writeValue(stream, value.raw)
      }
      is WallpaperSourceData -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is TargetResultData -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is OperationResultData -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is WallpaperCapabilitiesData -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is StaticWallpaperRequestData -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is VideoWallpaperRequestData -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is OpenGlWallpaperRequestData -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is MaterialYouSupportData -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RotationSourceData -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is WallpaperRotationConfigData -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is WallpaperRotationStatusData -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface WallpaperApi {
  fun getPlatformVersion(callback: (Result<String>) -> Unit)
  fun checkMaterialYouSupport(callback: (Result<MaterialYouSupportData>) -> Unit)
  /** Returns the platform's structured wallpaper capabilities. */
  fun getCapabilities(callback: (Result<WallpaperCapabilitiesData>) -> Unit)
  /** Applies a static wallpaper using the structured 3.2 transport contract. */
  fun applyWallpaper(request: StaticWallpaperRequestData, callback: (Result<OperationResultData>) -> Unit)
  /** Prepares a video live wallpaper without claiming that it was applied. */
  fun prepareVideoWallpaper(request: VideoWallpaperRequestData, callback: (Result<OperationResultData>) -> Unit)
  /** Opens the live-wallpaper UI and reports that distinct outcome. */
  fun openLiveWallpaperPreview(request: VideoWallpaperRequestData, callback: (Result<OperationResultData>) -> Unit)
  /** Applies a shader-based OpenGL live wallpaper. */
  fun applyOpenGlWallpaper(request: OpenGlWallpaperRequestData, callback: (Result<OperationResultData>) -> Unit)
  fun setMaterialYouWallpaper(url: String, callback: (Result<Boolean>) -> Unit)
  fun openWallpaperChooser(callback: (Result<Boolean>) -> Unit)
  fun downloadWallpaper(url: String, callback: (Result<Boolean>) -> Unit)
  fun startWallpaperRotation(config: WallpaperRotationConfigData, callback: (Result<Boolean>) -> Unit)
  fun stopWallpaperRotation(callback: (Result<Boolean>) -> Unit)
  fun getWallpaperRotationStatus(callback: (Result<WallpaperRotationStatusData>) -> Unit)
  fun rotateWallpaperNow(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by WallpaperApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonApiPigeonCodec()
    }
    /** Sets up an instance of `WallpaperApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WallpaperApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformVersion{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.checkMaterialYouSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkMaterialYouSupport{ result: Result<MaterialYouSupportData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCapabilities{ result: Result<WallpaperCapabilitiesData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.applyWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as StaticWallpaperRequestData
            api.applyWallpaper(requestArg) { result: Result<OperationResultData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.prepareVideoWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoWallpaperRequestData
            api.prepareVideoWallpaper(requestArg) { result: Result<OperationResultData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openLiveWallpaperPreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoWallpaperRequestData
            api.openLiveWallpaperPreview(requestArg) { result: Result<OperationResultData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.applyOpenGlWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as OpenGlWallpaperRequestData
            api.applyOpenGlWallpaper(requestArg) { result: Result<OperationResultData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.setMaterialYouWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.setMaterialYouWallpaper(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.openWallpaperChooser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openWallpaperChooser{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.downloadWallpaper$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.downloadWallpaper(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.startWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as WallpaperRotationConfigData
            api.startWallpaperRotation(configArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.stopWallpaperRotation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopWallpaperRotation{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.getWallpaperRotationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getWallpaperRotationStatus{ result: Result<WallpaperRotationStatusData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.async_wallpaper.WallpaperApi.rotateWallpaperNow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.rotateWallpaperNow{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
